### ISSUE TITLE
I don't see the custom parameters in the view

### ISSUE THREAD

**Issue by Sgiostra-BitBang** [Velir/dbt-ga4#113]
Hi @dgitis,
I've a problem with custom parameters.   

I wish to have the details of event **purchase**, so I added:
```
    purchase_custom_parameters:
      - name: "value"
        value_type: "float_value"
      - name: "currency"
        value_type: "string_value"
      - name: "transaction_id"
        value_type: "string_value"
```

in
```
vars:
  ga4:
```
of _dbt_project.yml_

I also added the file **staging/stg_ga4__event_purchase.sql** in **models**, made in this way:
```SQL
 with purchase_with_params as (
   select *,
      {% if var("purchase_custom_parameters", "none") != "none" %}
        {{ ga4.stage_custom_parameters( var("purchase_custom_parameters") )}}
      {% endif %}
 from {{ref('stg_ga4__events')}}    
 where event_name = 'purchase'
)

select * from purchase_with_params
```

At end I have the view **stg_ga4__event_purchase**, but in the view i don't see the columns that i signed in **purchase_custom_parameters**.

And don't understand the cause of the issue.

Thanks

_Originally posted by @Sgiostra-BitBang in https://github.com/Velir/dbt-ga4/issues/108#issuecomment-1406382115_

**Comment by adamribaudo-velir** [comment]
@Sgiostra-BitBang the package already contains a purchase event model here with those parameters: https://github.com/Velir/dbt-ga4/blob/main/models/staging/ga4/recommended_events/stg_ga4__event_purchase.sql

Why not use that?

**Comment by Sgiostra-BitBang** [comment]
Hi @adamribaudo-velir
ok, with 
```
models:
  ga4:
    staging:
      ga4:
        recommended_events:
          stg_ga4__event_purchase:
            +enabled: true
```

works, thanks, and now i have wath i need in this  moment, but i think it is still important to understand why the **custom parameters** option don't works  (at least for me).

**Comment by adamribaudo-velir** [comment]
My guess is that your model name conflicted with the package model name. They were both `stg_ga4__event_purchase.sql`

**Comment by Sgiostra-BitBang** [comment]
Now I changed the name of the view in **purchase_sg** (path: models/staging/purchase_sg.sql)
As described here: https://github.com/Velir/dbt-ga4/blob/main/README.md#custom-parameters
The file _purchase_sg.sql_ is made in this way:
```SQL
 with purchase_with_params as (
   select 'sg' as owner,
      {% if var("purchase_sg_custom_parameters", "none") != "none" %}
        {{ ga4.stage_custom_parameters( var("purchase_sg_custom_parameters") )}}
      {% endif %}
 from {{ref('stg_ga4__events')}}    
 where event_name = 'purchase'
)
select * from purchase_with_params
```

and in _dbt_project.yml_ I have:
```yaml
vars:
  ga4:
    project: "********************"
    dataset: "analytics_********"
    start_date: "20220101" # Earliest date to load
    frequency: "daily" # daily|streaming|daily+streaming.

    purchase_sg_custom_parameters:
      - name: "value"
        value_type: "float_value"
      - name: "currency"
        value_type: "string_value"
      - name: "transaction_id"
        value_type: "string_value"

    conversion_events: ["add_payment_info", "add_shipping_info", "add_to_cart", "add_to_wishlist", "begin_checkout", "generate_lead"
                      , "purchase", "refund", "remove_from_cart", "select_item", "select_promotion", "view_cart", "view_item", "view_item_list"
                      , "view_promotion"]

```
But on generated view i still to don't see the custom parametes, infact the view generated is made in this way:
```SQL
with purchase_with_params as (
   select 'sg' as owner,
      
 from `sigma-task-728`.`dbt_ga4_data_model`.`stg_ga4__events`    
 where event_name = 'purchase'
)
select * from purchase_with_params
```

**Comment by willbryant** [comment]
The `purchase_sg_custom_parameters` is under `ga4` but your file `models/staging/purchase_sg.sql` is not in a `ga4` directory, therefore I believe it won't get given the variable by DBT.

Try `models/staging/ga4/purchase_sg.sql`?

**Comment by Sgiostra-BitBang** [comment]
Hi @willbryant,
I also think that the issue is generated from how  the table/view is signed in _module_ section in **dbt_project.yml** and how the macro _dbt_packages/ga4/macros/stage_custom_parameters.sql_ can associate the field defined in the section with the parameter passed to his call in the code of the view:
`{{ ga4.stage_custom_parameters( var("purchase_sg_custom_parameters") )}}`

If i will understand which is the **_correct way_** to write these 2 vales  I'm sure that I will resolve this  issue.
The question is: how must be setted the table/view path in the **model** section of **dbt_project.yml** and how i must set the **\<table/view\>_custom_parameters** key when it is used as parameter of **ga4.stage_custom_parameters** ?

**Comment by willbryant** [comment]
The custom variables need to go in the vars section, not the model section.

**Comment by Sgiostra-BitBang** [comment]
Hi, @willbryant, thanks! 
Moving the defition of the custom_parameters in the **var** section e removing the **staging** _subset_ I finally have the view with the _custom_ columns.

now the **var** section  in my **dbt_project.yml** is in this way:
```yaml
vars:
  ga4:
    project: ".........."
    dataset: ".........."
    start_date: "20220101" # Earliest date to load
    frequency: "daily" # daily|streaming|daily+streaming.

    conversion_events: ["add_payment_info", "add_shipping_info", "add_to_cart", "add_to_wishlist", "begin_checkout", "generate_lead"
                      , "purchase", "refund", "remove_from_cart", "select_item", "select_promotion", "view_cart", "view_item", "view_item_list"
                      , "view_promotion"]
    
  bb_g4_data_model:
    purchase_sg_custom_parameters:
      - name: "value"
        value_type: "double_value"
      - name: "currency"
        value_type: "string_value"
      - name: "transaction_id"
        value_type: "string_value"

```
