### ISSUE TITLE
Remove models/staging/ga4 folder and move staging models under /models/staging?

### ISSUE THREAD

**Issue by adamribaudo-velir** [Velir/dbt-ga4#142]
When I started this package, I put the models under /models/staging/ga4 because typically I put staging models under a folder named after the source of data. This, however, creates confusing situations where users need to select package models using this selection criteria: `ga4.staging.ga4.MODEL` and this project config:

```
models:
  ga4:
    staging:
      ga4:
        recommended_events:
          stg_ga4__event_sign_up:
            +enabled: true
          stg_ga4__event_share:
            +enabled: true
```

It also seems unnecessary because ALL data in this package is sourced from ga4. It would be much cleaner to remove the /models/staging/ga4 folder. But this would be a breaking change for some folks who reference those paths.

Thoughts?
