### ISSUE TITLE
Output of marts vs staging

### ISSUE THREAD

**Issue by analyst-usafacts** [Velir/dbt-ga4#275]
Hey there,

I just found your package and it is awesome. 
I want to materialize the output of the models on different schemas / datasets, I have this configuration but when I ran the model in my PROD deployment, everything gets written in PROD instead of PROD & STAGING. What am I doing wrong?

```
models:
  my_dbt_project:
    reports:
      +materialized: view
    ga4:
      +tags: "googleanalytics"
      marts:
        +schema: prod
      staging:
        +schema: staging


vars:
  ga4:
    project: "my_bq_project"
    dataset: "my_bq_dataset"
    start_date: "20230701"
    static_incremental_days: 3
```

<img width="421" alt="image" src="https://github.com/Velir/dbt-ga4/assets/147658945/7888f30f-e87d-4276-818b-61425ee470c1">
