### ISSUE TITLE
Earliest Date Not Aligned with Project var start_date

### ISSUE THREAD

**Issue by arodriguezdealeron** [Velir/dbt-ga4#278]
Hi! Hoping this is the right place to submit this issue.

I have recently implemented this package to handle much of the GA4 heavy-lifting in our org and so far it has proven infinitely more valuable than I thought possible.

That said, while populating my initial data set (the cutoff is 2023-07-01), the incremental tables created (base_ga4__events) only go back as far as 08-21 which is an odd date, though I have verified that the source data in GA4 goes back to 07-01 (analytics_296372144.events_20230701).

Confirmed date in the dbt log for base_ga4__events as well 

```
from `bigquery-dealeron-reporting`.`analytics_296372144`.`events_*`
where cast( replace(_table_suffix, 'intraday_', '') as int64) >= `20230701`
```

Didn't run into any timeout issues, but am at a loss.

Thanks.

**Comment by adamribaudo-velir** [comment]
Can you confirm what your `start_date` variable is set to in your `dbt_project.yml` file?

**Comment by arodriguezdealeron** [comment]
From project YML

```
vars:
  ga4:
    project: "bigquery-dealeron-reporting"
    dataset: "analytics_296372144"
    start_date: "20230701" # Earliest date to load
```
