### ISSUE TITLE
Field name item_params does not exist in STRUCT<item_id STRING, item_name STRING, item_brand STRING, ...>

### ISSUE THREAD

**Issue by erikverheij** [Velir/dbt-ga4#289]
Hello! I'm running into the following error:

```
Database Error in model base_ga4__events (models/staging/base/base_ga4__events.sql)
Field name item_params does not exist in STRUCT<item_id STRING, item_name STRING, item_brand STRING, ...>; Did you mean item_brand? at [157:30]
compiled Code at target/run/ga4/models/staging/base/base_ga4__events.sql
```

Do you have any idea what could be the issue? I've removed all tables from my dataset and tried to rebuild everything from scratch but still run into this error.

This is my project config:

```
name: bigquery_my-company_analytics
version: 0.0.1
config-version: 2
profile: bigquery_my-company_analytics

vars:
  static_incremental_days: 3
  ga4:
    project: my-company-analytics
    property_ids: [1234567, 2345678]
    dataset: analytics_dbt
    start_date: "20230501"
    conversion_events: ["purchase"]
    transaction_custom_parameters:
      - name: "transaction_id"
        value_type: "int_value"
    cta_click_custom_parameters:
      - name: "label"
        value_type: "string_value"
      - name: "tm_page"
        value_type: "string_value"
      - name: "tm_section"
        value_type: "string_value"
      - name: "tm_cta"
        value_type: "string_value"

models:
  ga4:
    staging:
      recommended_events:
        stg_ga4__event_purchase:
          +enabled: true
        stg_ga4__event_generate_lead:
          +enabled: true

```

I'm using package version `5.1.0`.

If I change `start_date` to 2023-11-01 it runs without errors. I'm not sure from which date it exactly starts to fail, but it's somewhere between `20230501` and `20231101`
