### ISSUE TITLE
Different row count between raw data from ga4 and base_ga4__events

### ISSUE THREAD

**Issue by tegardp** [Velir/dbt-ga4#297]
**Background**: I'm currently using this package to generate session based data based on ga4 events raw data. In order to migrate our company old data marts to use ga4 data.
**Problem Statement**: as the title says. 
**Steps to Reproduce**: Run this package and use your own raw data. check and compare count of raw table and base_ga4__events
**Expected**: the rows have same count
**Actual Behavior**: around 200k rows or 0.4% data points are missing.

Any info is there any configuration missing?

I only add config below in my dbt projects
```
vars:
  ga4:
    source_project: 
    property_ids: 
    start_date: "20240118" # Earliest date to load
    static_incremental_days: 3 # Number of days to scan and reprocess on each run
    query_parameter_exclusions: ["gclid","fbclid","_ga"] 
    query_parameter_extraction: ["gclid","fbclid","keyword"] 
    user_properties:
      - user_property_name: "some_property_name"
         value_type: "string_value"
```
