### ISSUE TITLE
Error in the base_ga4_events model

### ISSUE THREAD

**Issue by Frydafly** [Velir/dbt-ga4#313]
``` Value has type ARRAY<STRUCT<item_id STRING, item_name STRING, item_brand STRING, ...>> which cannot be inserted into column items, which has type ARRAY<STRUCT<item_id STRING, item_name STRING, item_brand STRING, ...>> at [260:1168]  
```

That is the error I keep getting for `base_ga4_events` when I run it in my dbt project. 

I am using version 4.0.0 because when I run dbt deps on any higher version, I get a failure in dbt deps regarding a nonetype object.

using 
vars:
ga4:
      project: "our-project-name"
      dataset: "our-dataset-name"
      start_date: "20230301" # Earliest date to load
      frequency: "daily" # daily|streaming|daily+streaming. See 'Export Frequency' below.

**Comment by dgitis** [comment]
The nonetype object error is because you are missing the `static_incremental_days` variable in your `dbt_project.yml` file.

Set that variable and the new `source_project` and `property_ids` variables, then upgrade and you should be fine.

```
vars:
  ga4:
    source_project: "my_source_gcp_project" # Project that contains raw GA4 data
    property_ids: [11111111] # Array of properties to process
    start_date: "YYYYMMDD" # Earliest date to load
    static_incremental_days: 3 # Number of days to scan and reprocess on each run
```
