### ISSUE TITLE
multi-property option to analyze properties seperately

### ISSUE THREAD

**Issue by tessa-beijloos** [Velir/dbt-ga4#318]
We can select multiple properties like this:
```
vars:
  ga4:
    property_ids: [11111111, 22222222, 33333333]
    static_incremental_days: 3
    combined_dataset: "my_combined_dataset"
```
And it then combines the dataset into one (with combined_property_data()). I need a way to analyze them seperately in the same project. Is there a workaround for this? Thanks in advance!
